name: Deployment on Merge
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
  pull-requests: write
  actions: read

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Download SF CLI and SGD Git Delta
        run: |
          npm install @salesforce/cli -g
          echo y | sf plugins install sfdx-git-delta

      - name: Get Commits
        env:
          GH_TOKEN: ${{github.token}}
        run: |
          echo "sourceCommitId=${{ github.sha }}" >> "$GITHUB_ENV"

          echo "targetBranch=${{ github.base_ref }}" >> "$GITHUB_ENV"

          last_successful_commit=$(gh api "repos/${{ github.repository }}/actions/workflows/Deployment.yaml/runs" \
          --jq '.workflow_runs[] | select(.head_branch=="'"$targetBranch"'") | select(.status=="completed") | select(.conclusion=="success") | .head_sha' \
          | head -1 || true)
          
          if [ -z "$last_successful_commit" ]; then
            last_successful_commit=$(git log --reverse --format=%H main | head -1)
          fi

          echo "last_successful_commit=$last_successful_commit" >> "$GITHUB_ENV"

      - name: Generate Package
        run: |
          set -euo pipefail
          sf sgd source delta --to $last_successful_commit --from $sourceCommitId --output-dir .
          if [ ! -f package/package.xml ]; then
            mkdir -p package
            echo '<?xml version="1.0" encoding="UTF-8"?><Package xmlns="http://soap.sforce.com/2006/04/metadata"><version>67.0</version></Package>' > package/package.xml
          fi

      - name: Authenticate SF ORG
        run: |
          echo "${{secrets.SFDX_AUTH_URL}}" > authurl.txt
          sf org login sfdx-url --sfdx-url-file authurl.txt --set-default --alias "DEVORG"
      
      - name: Download Package.xml
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: package/package.xml
      
      - name: Deploy
        run: |
          if grep -q '<types>' package/package.xml; then
            sf project deploy start -x package/package.xml -l NoTestRun
          else
            echo "No Changes to Deploy"
          fi
