name: Validation on Pull Request
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  VALIDATE:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Download SF CLI and SGD Git Delta
        run: |
          npm install @salesforce/cli -g
          echo y | sf plugins install sfdx-git-delta

      - name: Get Commits
        run: |
          echo "sourceCommitId=${{ github.sha }}" >> "$GITHUB_ENV"
          #echo "SOURCE_COMMIT_ID=$(git log --oneline | tail -1 | grep "commit" | cut -d' ' -f 1)" >> "$GITHUB_ENV"
          echo "targetBranch=${{ github.base_ref }}" >> "$GITHUB_ENV"
          echo "workflowId=${{ github.workflow }}" >> "$GITHUB_ENV"
          gh_command="gh api repos/Commit-Craft/ExpenseTracker/actions/workflows/$workflowId/runs --jq '.workflow_runs[] | select(.head_branch == \"$targetBranch\") | select(.status == \"completed\") | select(.conclusion == \"success\") | .head_sha' | head -1"
          echo "last_successful_commit=$(eval $gh_command)" >> "$GITHUB_ENV"
      - name: Generate Package
        run: |
          sf sgd source delta --to $sourceCommitId --from $last_successful_commit --output-dir .

      - name: Authenticate SF ORG
        run: |
          echo "${{secrets.SFDX_AUTH_URL}}" > authurl.txt
          sf org login sfdx-url --sfdx-url-file authurl.txt --set-default --alias "DEVORG"
      
      - name: Download Package.xml
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: package/package.xml
      - name: Validate
        run: |
          if grep -q '<types>' package/package.xml; then
            sf project deploy start -x package/package.xml -l RunSpecifiedTests --tests "RecurringPaymentSchedulerTest"
          else
            echo "No Changes to Validate"
          fi
